Repository w3b3d3v/web3task-front, pull requests merged in 2023-10, with the labels that each got.

#81 Feat: implementation of setQuorum and deposit on the adminOptions
  src/content/applications/Tasks/settings/AdminOptions.tsx
  src/contracts/31337/TasksManager.json
  src/hooks/TaskServiceHook.tsx
  src/hooks/Web3UtilsHook.tsx
  src/services/tasks-service.ts
Labels: dog

#88 Feat: Adjust Filter bg Transparent && Calendar Icons && Layout Page
  public/static/images/task/home/filtro.svg
  public/static/images/task/home/filtroIcon.svg
  src/components/Task/CardMultiTasks.tsx
  src/components/Task/SearchFiltersTasks.tsx
  src/content/applications/Tasks/HomeTasks.tsx
  src/content/applications/Tasks/settings/CreateTask.tsx
  src/theme/schemes/DarkTheme.ts
  src/theme/schemes/LightTheme.ts
Labels: enhancement, turtle

#99 feat: better task card UI with charming close buttom and description field
  src/components/Task/CardTask.tsx
  src/content/applications/Tasks/details/DetailsTask.tsx
Labels: enhancement

#111 fix: removing local files from the environment
  .gitignore
  package-lock.json
  yarn.lock
Labels: enhancement

#114 fix: score not loading, tooltip for reviewing task, mismatching currency symbol
  src/components/Task/CardMultiTasks.tsx
  src/components/Task/CardTask.tsx
  src/content/applications/Users/profile/UserProfile.tsx
Labels: bug
